# global list of Stockmarkets on finanzen.net their url components and real names
StockMarkets = {
    "BER": {"url_postfix": "@stBoerse_BER", "real_name": "Berlin"},
    "DUS": {"url_postfix": "@stBoerse_DUS", "real_name": "Düsseldorf"},
    "FSE": {"url_postfix": "@stBoerse_FSE", "real_name": "Frankfurt Stock Exchange"},
    "HAM": {"url_postfix": "stBoerse_HAM", "real_name": "Hamburg"},
    "HAN": {"url_postfix": "@stBoerse_HAN", "real_name": "Hannover"},
    "MUN": {"url_postfix": "@stBoerse_MUN", "real_name": "München"},
    "XETRA": {"url_postfix": "@stBoerse_XETRA", "real_name": "XETRA"},
    "STU": {"url_postfix": "@stBoerse_STU", "real_name": "Stuttgard"},
    "TGT": {"url_postfix": "@stBoerse_TGT", "real_name": "Tradegate"},
    "BAE": {"url_postfix": "@stBoerse_BAE", "real_name": "Baader Bank"},
    "BDP": {"url_postfix": "@stBoerse_BDP", "real_name": "Budapest"},
    "BRX": {"url_postfix": "@stBoerse_BRX", "real_name": "BX SWISS"},
    "BTE": {"url_postfix": "@stBoerse_BTE", "real_name": "Bats"},
    "BTT": {"url_postfix": "@stBoerse_BTT", "real_name": ""},
    "CLB": {"url_postfix": "@stBoerse_CLB", "real_name": ""},
    "GVIE": {"url_postfix": "@stBoerse_GVIE", "real_name": "Global Market"},
    "NAS": {"url_postfix": "@stBoerse_NAS", "real_name": "NASDAQ OTC"},
    "MXK": {"url_postfix": "@stBoerse_MXK", "real_name": ""},
    "SIX": {"url_postfix": "@stBoerse_SWX", "real_name": "SIX Swiss Exchange"},
    "XQTX": {"url_postfix": "@stBoerse_XQTX", "real_name": "Quotrix"},
    "AMEX": {"url_postfix": "@stBoerse_AMEX", "real_name": ""},
    "NYSE": {"url_postfix": "@stBoerse_NYSE", "real_name": "New York Stock Exchange"},
}
